using System;
using System.Collections.Generic;

namespace BusinessObjects.Model
{
/// <summary>
/// Product model class
/// </summary>
    public class Product
    {
        //Unique ID (autogenerated during POST process)
        public Guid Id { get; set; }
        //Object Name
        public string Name { get; set; } = null!;
        //Object Description
        public string? Description { get; set; }
    }
}
